
CREATE TABLE requests (
	id 					INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ip_address_hash		VARCHAR(256) NOT NULL,
	path				TEXT NOT NULL,
	method				UNSIGNED TINYINT NOT NULL,
	status				UNSIGNED SMALLINT NOT NULL,
	created_at			UNSIGNED INTEGER NOT NULL
);
